spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: bank
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://172.20.0.2:8761/eureka}
    register-with-eureka: true


server:
  ssl:
    enabled: true
    trust-store-type: jks
    trust-store: file:truststore.jks
    trust-store-password: 123456

  port: ${PORT:8442}

keygen:
  token: EeyvFhsQvWXLvGllldytegnjPZ3B2poNGf7oNgk2OEO3xT1JnlfQALeguuDbzxNo

root-url: http://localhost/bank/
